name: xibalba-client

services:
  explorer:
    image: oven/bun:latest
    working_dir: /app
    command: [
      "bun",
      "run",
      "--cwd",
      "apps/explorer",
      "vite",
      "dev",
      "--host",
      "0.0.0.0",
      "--port",
      "5173",
    ]
    ports:
      - "5173:5173"
    volumes:
      - .:/app

  vision:
    image: oven/bun:latest
    working_dir: /app
    command: [
      "bun",
      "run",
      "--cwd",
      "apps/vision",
      "vite",
      "dev",
      "--host",
      "0.0.0.0",
      "--port",
      "5174",
    ]
    ports:
      - "5174:5174"
    volumes:
      - .:/app
